name: publish Docker image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          docker build -t phhe002 .
          docker tag phhe002:latest 244530008913.dkr.ecr.eu-west-1.amazonaws.com/phhe002:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/phhe002:latest